### ISSUE TITLE
Create的新渲染方式導致遊戲崩潰

### ISSUE THREAD

**Issue by youchen624** [joker876/The-Creative-Skyblock#1]
Create的方塊出現在渲染區域會導致Win7版本電腦崩潰 而無法遊戲
The Create block appears in the rendering area and will cause the Win7 version of the computer to crash and the game cannot be played.
已附上.log 崩潰報告
[hs_err_pid14528.log](https://github.com/joker876/The-Creative-Skyblock/files/6572950/hs_err_pid14528.log)

**Comment by joker876** [comment]
This seems to be an issue with the Create mod itself, and thus I am not able to fix that.

**Comment by youchen624** [comment]
OK
