### ISSUE TITLE
What Language does this modpacks have?

### ISSUE THREAD

**Issue by haolinchennnxsalkjx** [joker876/The-Creative-Skyblock#2]
I see a Chinese youtuber play this modpack, he is a nice youtuber, then i also want to play this modpack,then i just want to makes sure this modpack have chinese, or i need the translate mod

**Comment by joker876** [comment]
The language availability depends on whether or not the individual mods support Chinese. The only thing that I can translate is the main menu, and you can help with that if you want. 

By the way, can you link to the Youtuber's channel?

**Comment by haolinchennnxsalkjx** [comment]
yes, Onityan - YouTube <https://www.youtube.com/c/Onityan/videos> here is
link, this is a good youtuber

**Comment by haolinchennnxsalkjx** [comment]
and what help do you need to translate??

**Comment by joker876** [comment]
Well, all the texts in the main menu need to be translated. I will also see if quests are able to be translated as well, and if they are, then I will let you know.

**Comment by haolinchennnxsalkjx** [comment]
ok, i am happy i can join it.
